---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
      - id: check-yaml
      - id: check-case-conflict
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.23.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.3.0a1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
