repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
        files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-json
    -   id: end-of-file-fixer
-   repo: https://github.com/willthames/ansible-lint.git
    rev: v3.4.23
    hooks:
    -   id: ansible-lint
        files: \.(yaml|yml)$
        args:
        - --exclude=.travis.yml
#-   repo: local
#    hooks:
#    -   id: travis-lint
#        name: Travis Lint
#        entry: bundle
#        language: system
#        files: ^\.travis\.yml$
#        args:
#        - exec
#       - travis
#        - lint
#        - --no-interactive
#        - --skip-version-check
#        - --skip-completion-check
#        - --exit-code
