---
dependency:
  name: gilt
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: "centos6"
    image: "geerlingguy/docker-centos6-ansible"
    pull: true
    pre_build_image: true
    command: "/sbin/init"
  - name: "centos7"
    image: "centos/systemd:latest"
    pull: true
    pre_build_image: false
    command: "/usr/sbin/init"
    # https://github.com/ansible/ansible/issues/18692
    kill_signal: "RTMIN+3"
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/run"
  - name: "debian9"
    image: "bdellegrazie/debian-systemd:9"
    groups:
      - python_3
    pull: true
    pre_build_image: true
    command: "/sbin/init"
    # https://github.com/ansible/ansible/issues/18692
    kill_signal: "RTMIN+3"
    capabilities:
      - SYS_ADMIN
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/run"
      - "/tmp"
  - name: "ubuntu1804"
    image: "bdellegrazie/ubuntu-systemd:18.04"
    groups:
      - python_3
    pull: true
    pre_build_image: true
    command: "/sbin/init --log-target=journal"
    kill_signal: "RTMIN+3"
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    tmpfs:
      - "/tmp"
      - "/run"
      - "/run/lock"
provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: jsonfile
      fact_caching_connection: $MOLECULE_EPHEMERAL_DIRECTORY/.facts
      fact_caching_timeout: 600
      gather_timeout: 20
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      python_3:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: yamllint
